services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports: ["3000:3000"]
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/personal-website
  db:
    image: postgres:17-alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: personal-website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes: ["pgdata:/var/lib/postgresql/data"]

volumes:
  pgdata:
